/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Dialog;
import GUI.AdminDashboardGUI;
import Controller.StudioController;
import model.Studio;


import GUI.AdminDashboardGUI;
import javax.swing.JOptionPane;

/**
 *
 * @author nyoma
 */
public class FormAddStudioGUI extends javax.swing.JDialog {

    private final AdminDashboardGUI parentFrame;
    private final StudioController studioController;
    /**
     * Creates new form FormAddStudioGUI
     */
    public FormAddStudioGUI(AdminDashboardGUI parent, boolean modal) {
        super(parent, modal);
        this.parentFrame = parent;
        initComponents();
        
        this.studioController = new StudioController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        idStudioLabel = new javax.swing.JLabel();
        fasilitasLabel = new javax.swing.JLabel();
        kapasitasLabel = new javax.swing.JLabel();
        hargaLabekl = new javax.swing.JLabel();
        idStudioTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fasilitasTextArea = new javax.swing.JTextArea();
        kapasitasTextField = new javax.swing.JTextField();
        hargaTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 0, 0));
        titleLabel.setText("TAMBAH STUDIO BARU");

        idStudioLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idStudioLabel.setForeground(new java.awt.Color(0, 0, 0));
        idStudioLabel.setText("ID Studio:");

        fasilitasLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fasilitasLabel.setForeground(new java.awt.Color(0, 0, 0));
        fasilitasLabel.setText("Fasilitas:");

        kapasitasLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kapasitasLabel.setForeground(new java.awt.Color(0, 0, 0));
        kapasitasLabel.setText("Kapasitas:");

        hargaLabekl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hargaLabekl.setForeground(new java.awt.Color(0, 0, 0));
        hargaLabekl.setText("Harga/jam:");

        idStudioTextField.setForeground(new java.awt.Color(0, 0, 0));

        fasilitasTextArea.setColumns(20);
        fasilitasTextArea.setForeground(new java.awt.Color(0, 0, 0));
        fasilitasTextArea.setRows(5);
        jScrollPane1.setViewportView(fasilitasTextArea);

        kapasitasTextField.setForeground(new java.awt.Color(0, 0, 0));
        kapasitasTextField.setToolTipText("");

        hargaTextField.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(hargaLabekl)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kapasitasLabel)
                                    .addComponent(fasilitasLabel)
                                    .addComponent(idStudioLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idStudioTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(kapasitasTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(titleLabel)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idStudioLabel)
                    .addComponent(idStudioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fasilitasLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kapasitasLabel)
                    .addComponent(kapasitasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaLabekl)
                    .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String newIdStudio = idStudioTextField.getText();
        String newFasilitas = fasilitasTextArea.getText();
        String newKapasitas = kapasitasTextField.getText();
        String newPrice = hargaTextField.getText();
        
        try
        {
            int kapasitas = Integer.parseInt(newKapasitas);
            int harga = Integer.parseInt(newPrice);
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menambahkan data studio\nberu dengan ID: " + newIdStudio + "?",
                "Konfirmasi", JOptionPane.YES_NO_OPTION);
            
            if (confirm == JOptionPane.YES_OPTION)
            {
                Studio studio = new Studio(newIdStudio, newFasilitas, kapasitas, harga);
                boolean success = studioController.insertStudio(studio);
                if (success)
                {
                   JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                   AdminDashboardGUI loadStudioTable = new AdminDashboardGUI();
                   loadStudioTable.loadStudioTable();
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Gagal menambahkan data!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddStudioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddStudioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddStudioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddStudioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormAddStudioGUI dialog = new FormAddStudioGUI(new AdminDashboardGUI(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fasilitasLabel;
    private javax.swing.JTextArea fasilitasTextArea;
    private javax.swing.JLabel hargaLabekl;
    private javax.swing.JTextField hargaTextField;
    private javax.swing.JLabel idStudioLabel;
    private javax.swing.JTextField idStudioTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kapasitasLabel;
    private javax.swing.JTextField kapasitasTextField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
